development: &default
  adapter: postgresql
  database: Rails106_development
  encoding: unicode
  pool: 5
  reaping_frequency: 10
  username:
  password:

test:
  <<: *default
  database: Rails106_test

production:
  <<: *default
  database: Rails106_production
